kind: pipeline
type: docker
name: deploy-docker-react

workspace:
  path: /app

steps:
  - name: frontend
    image: node:16-alpine
    commands:
      - yarn install
      - yarn test -- --coverage
      - yarn build
  - name: proxy
    image: nginx:1.23-alpine
    depends_on: [frontend]
    commands:
      - pwa
      - cp -f /app/build /usr/share/nginx/html
  