kind: pipeline
type: docker
name: deploy-docker-react

workspace:
  path: /app

steps:
  # - name: frontend
  #   image: node:16-alpine
  #   commands:
  #     - yarn install
  #     - yarn test -- --coverage
  - name: frontend
    image: plugins/docker
    commands:
      - sudo docker image build -t jc/docker-react .
      - sudo docker container run jc/docker-react yarn test -- --coverage
    settings:
      dockerfile: .
