kind: pipeline
type: docker
name: deploy-docker-react

workspace:
  path: /app

steps:
  - name: frontend
    image: node:16-alpine
    environment:
      CI: true
    commands:
      - yarn install
      - yarn test -- --coverage
      - yarn build
  - name: proxy
    image: nginx:1.23-alpine
    depends_on: [frontend]
    commands:
      - pwd
      - cp -r /app/build /usr/share/nginx/html
  - name: docker  
    image: plugins/docker
    settings:
      username: jerremychen
      password: 1qaz@WSX3edc
      repo: jc/docker-react
      tags: latest