version: '3'

services:
  web:
    image: jc-web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - "/app/node_modules"
      - ".:/app"
  tests:
    image: jc-tests
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - ".:/app"
    command: [ "yarn", "test" ]
